model:
  arch: caption_coco_tinystories33m
  load_finetuned: True

  pretrained: "lavis/output/BLIP2/Pretrain_stage2_tinystories33m-finetuned/20240210231/checkpoint_0.pth"
  finetuned: "lavis/output/BLIP2/Pretrain_stage2_tinystories33m-finetuned/20240210231/checkpoint_0.pth"

  # vit encoder
  image_size: 364
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp32"
  freeze_vit: False

  # Q-Former
  num_query_token: 32

  # TinyStories
  # tinystories_model: "roneneldan/TinyStories-33M"
  tinystories_model: "/extra/workspaces/ml/lavis-experiments/tinystories-finetune/finetune-tinystories/finetuned/checkpoint-5500"

  # generation configs
  prompt: "a picture of"


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 364
        eval:
          name: "blip_image_eval"
          image_size: 364
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
